// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaVJNUEKIpVvRbTutKCJxNUI3prCMphBg',
    appId: '1:84894115804:web:2562f78b1af70f8fb5d119',
    messagingSenderId: '84894115804',
    projectId: 'alertalima-bed21',
    authDomain: 'alertalima-bed21.firebaseapp.com',
    storageBucket: 'alertalima-bed21.firebasestorage.app',
    measurementId: 'G-N6YP7V2PN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAxkwowD8_QCP-miyFbE_y68F1Ocldi0',
    appId: '1:84894115804:android:a043e2d515737b2fb5d119',
    messagingSenderId: '84894115804',
    projectId: 'alertalima-bed21',
    storageBucket: 'alertalima-bed21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLd0EKcGltLnsC6XdoiqTe9eH3AAPu21U',
    appId: '1:84894115804:ios:6b526157823653b9b5d119',
    messagingSenderId: '84894115804',
    projectId: 'alertalima-bed21',
    storageBucket: 'alertalima-bed21.firebasestorage.app',
    iosBundleId: 'com.example.alertaLima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLd0EKcGltLnsC6XdoiqTe9eH3AAPu21U',
    appId: '1:84894115804:ios:6b526157823653b9b5d119',
    messagingSenderId: '84894115804',
    projectId: 'alertalima-bed21',
    storageBucket: 'alertalima-bed21.firebasestorage.app',
    iosBundleId: 'com.example.alertaLima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaVJNUEKIpVvRbTutKCJxNUI3prCMphBg',
    appId: '1:84894115804:web:0113a42b695b2849b5d119',
    messagingSenderId: '84894115804',
    projectId: 'alertalima-bed21',
    authDomain: 'alertalima-bed21.firebaseapp.com',
    storageBucket: 'alertalima-bed21.firebasestorage.app',
    measurementId: 'G-JEKF86W9ZB',
  );
}
